//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.24 at 04:29:07 PM CEST 
//


package https.tempuri;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.tempuri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PasswordRequestQueryFormat_QNAME = new QName("https://tempuri.org/", "QueryFormat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.tempuri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPassword }
     * 
     */
    public GetPassword createGetPassword() {
        return new GetPassword();
    }

    /**
     * Create an instance of {@link PasswordRequest }
     * 
     */
    public PasswordRequest createPasswordRequest() {
        return new PasswordRequest();
    }

    /**
     * Create an instance of {@link GetPasswordResponse }
     * 
     */
    public GetPasswordResponse createGetPasswordResponse() {
        return new GetPasswordResponse();
    }

    /**
     * Create an instance of {@link PasswordResponse }
     * 
     */
    public PasswordResponse createPasswordResponse() {
        return new PasswordResponse();
    }

    /**
     * Create an instance of {@link Keyandvalue }
     * 
     */
    public Keyandvalue createKeyandvalue() {
        return new Keyandvalue();
    }

    /**
     * Create an instance of {@link ArrayOfKeyAndValue }
     * 
     */
    public ArrayOfKeyAndValue createArrayOfKeyAndValue() {
        return new ArrayOfKeyAndValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PasswordQueryFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://tempuri.org/", name = "QueryFormat", scope = PasswordRequest.class, defaultValue = "Exact")
    public JAXBElement<PasswordQueryFormat> createPasswordRequestQueryFormat(PasswordQueryFormat value) {
        return new JAXBElement<PasswordQueryFormat>(_PasswordRequestQueryFormat_QNAME, PasswordQueryFormat.class, PasswordRequest.class, value);
    }

}
